web.upload-path: D:/gitWorkSpace/admgc/src/main/resources/static

spring:
  resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admgc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
  devtools:
    restart:
            #热部署生效
      enabled: true
            #设置重启的目录
            #additional-paths: src/main/java
            #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: static/**,public/**,templates/**
  freemarker.template-loader-path: classpath:/templates
server.port: 80
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

kaptcha:
  width: 350
  content:
    length: 4
    space: 5
  font.color: black
site.config:
    dbname: admgc
    path: siteConfig.xml
    templatePath: inner/structure.ftl
logging.level.net.moonj.admgc.genecode.member.mapper: TRACE


