# # mybatis.type-aliases-package=net.moonj.demo.vo
# # \u672C\u6B21\u4F7F\u7528MybatisGenerator\u6CA1\u6709\u4F7F\u7528alias
# spring.datasource.driverClassName = com.mysql.jdbc.Driver
# spring.datasource.url = jdbc:mysql://localhost:3306/admgc?useUnicode=true&characterEncoding=utf-8
# spring.datasource.username = root
# spring.datasource.password = admin
# server.port=80
# # mybatis.mapperLocations=classpath:net/moonj/demo/vo/mapping/*.xml
# #\u8BBE\u5B9Aftl\u6587\u4EF6\u8DEF\u5F84
# spring.freemarker.template-loader-path=classpath:/templates
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admgc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
  devtools:
    restart:
            #热部署生效
      enabled: true
            #设置重启的目录
            #additional-paths: src/main/java
            #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: static/**,public/**,templates/**
  freemarker.template-loader-path: classpath:/templates
server.port: 80
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

site.config:
    dbname: admgc
    path: siteConfig.xml
    templatePath: inner/structure.ftl
logging.level.net.moonj.admgc.genecode.member.mapper: TRACE